version: '3.7'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production

  db:
    image: postgres:13
    container_name: flask_app_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  
