services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    # Добавьте переменные для подключения к БД
      - DATABASE_URL=postgresql://user:password@db:5432/notes_db

  db:
    image: postgres:13
    container_name: flask_app_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    # Порт 5432 можно не пробрасывать наружу (если БД используется только внутр>
    # ports:
    #   - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: