# security/.bandit.yml
targets:
  - app/
  
exclude:
  - venv/  # Исключить виртуальное окружение
  - tests/

skips:
  - B104  # Игнорировать hardcoded пароли
  - B602  # Игнорировать subprocess без shell=True

severity:
  - low
  - medium

confidence:
  - low
  - medium

aggregate:
  file: true
