name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  DB_PATH: "instance/site.db"
  STAGE_SERVER: "172.20.10.7"
  PROD_SERVER: "172.20.10.3"

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: SQL Security Check
        run: |
          pip install sqlfluff
          sqlfluff lint migrations/versions/ --dialect sqlite

  migrations:
    runs-on: ubuntu-latest
    needs: security-check
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install alembic

      - name: Run migrations
        run: |
          alembic upgrade head

  deploy-stage:
    runs-on: ubuntu-latest
    needs: [security-check, migrations]
    environment: stage
    steps:
      - uses: actions/checkout@v4
      
      - name: Compare schemas
        run: |
          ssh test@172.20.10.6 "sqlite3 /path/to/test.db .schema" > test_schema.sql
          ssh stage@172.20.10.7 "sqlite3 /path/to/stage.db .schema" > stage_schema.sql
          diff test_schema.sql stage_schema.sql || exit 1

      - name: Apply to Stage
        run: |
          scp -r . stage@${{ env.STAGE_SERVER }}:/app
          ssh stage@${{ env.STAGE_SERVER }} "cd /app && alembic upgrade head"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-stage
    environment: prod
    steps:
      - uses: actions/checkout@v4
      
      - name: Manual Approval
        uses: trstringer/manual-approval@v1

      - name: Deploy to Prod
        run: |
          scp -r . prod@${{ env.PROD_SERVER }}:/app
          ssh prod@${{ env.PROD_SERVER }} "cd /app && alembic upgrade head"
