name: CI/CD Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  DB_PATH: "/home/test/DevOps/instance/site.db"

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: SQL Security Check
        run: |
          pip install sqlfluff
          sqlfluff lint migrations/versions/ --dialect sqlite

  deploy-stage:
    runs-on: ubuntu-latest
    needs: security-check
    environment: stage
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Compare DB schemas
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.TEST_USER }}@${{ secrets.TEST_SERVER }} "sqlite3 ${{ env.DB_PATH }} '.schema'" > test_schema.sql
          ssh -o StrictHostKeyChecking=no ${{ secrets.STAGE_USER }}@${{ secrets.STAGE_SERVER }} "sqlite3 ${{ env.DB_PATH }} '.schema'" > stage_schema.sql
          diff test_schema.sql stage_schema.sql || exit 1

      - name: Deploy to Stage
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.STAGE_USER }}@${{ secrets.STAGE_SERVER }}:/home/test/DevOps/
          ssh -o StrictHostKeyChecking=no ${{ secrets.STAGE_USER }}@${{ secrets.STAGE_SERVER }} "cd /home/test/DevOps && alembic upgrade head"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-stage
    environment: prod
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Manual Approval
        uses: trstringer/manual-approval@v1

      - name: Deploy to Prod
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.PROD_USER }}@${{ secrets.PROD_SERVER }}:/home/test/DevOps/
          ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_SERVER }} "cd /home/test/DevOps && alembic upgrade head"
