name: Deploy Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Проверьте имя секрета!

      - name: Trust SSH hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -v -H 172.20.10.6 >> $HOME/.ssh/known_hosts 2>&1
          ssh-keyscan -v -H 172.20.10.7 >> $HOME/.ssh/known_hosts 2>&1
          ssh-keyscan -v -H 172.20.10.3 >> $HOME/.ssh/known_hosts 2>&1

      - name: Deploy to Stage
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ stage@172.20.10.7:/home/test/DevOps/
          ssh -o StrictHostKeyChecking=no stage@172.20.10.7 "cd /home/test/DevOps && alembic upgrade head"

